[tool.poetry]
name = "fredapi_demo"
version = "0.1.0"
description = ""
authors = ["gray <colorfulgray0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fredapi = "^0.5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
