version: "2.2"
services:
  jobmanager:
    image: pyflink:latest
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./task:/tmp/task
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager1:
    image: pyflink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./task:/tmp/task
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2   