[tool.poetry]
name = "gradio-demo"
version = "0.1.0"
description = ""
authors = ["colorfulgray0 <colorfulgray0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gradio = "^4.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
