[project]
name = "yfinance_demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "ipykernel>=6.29.5",
    "yfinance>=0.2.54",
]
