# Generated by Django 4.2 on 2023-04-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "no",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("intro", models.CharField(max_length=1000, verbose_name="介绍")),
                ("is_hot", models.BooleanField(verbose_name="是否热门")),
            ],
            options={
                "db_table": "tb_subject",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "no",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("sex", models.BooleanField(default=True, verbose_name="性别")),
                ("birth", models.DateField(verbose_name="出生日期")),
                ("intro", models.CharField(max_length=1000, verbose_name="个人介绍")),
                (
                    "good_count",
                    models.IntegerField(
                        db_column="gcount", default=0, verbose_name="好评数"
                    ),
                ),
                (
                    "bad_count",
                    models.IntegerField(
                        db_column="bcount", default=0, verbose_name="差评数"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="sno",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api_provider_model.subject",
                    ),
                ),
            ],
            options={
                "db_table": "tb_teacher",
                "managed": True,
            },
        ),
    ]
